### ISSUE TITLE
/announcements breaks if any announcement has no description

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#888]
Steps to recreate:
1. Create an announcement w/o a description
2. Go to `/announcements`

Probably worth checking other Announcement pages and the landing page as well.

**Comment by samudary** [comment]
Hi @exbinary or @maebeale I'm thinking of picking this up but wanted some clarification on requirements. I tried creating an announcement both as an admin and unauthed but there's a UI validation that prevents submitting without a description. There's also a model validation should safeguard against this as well. So I'm not sure how to reproduce the issue

**Comment by maebeale** [comment]
@samudary hey! thanks for following up on this, and, excellent point! this error happens when we upgrade existing instances to the new requirements. they had announcements in the database when this wasn't a restriction. 

there are three ways to create underlying data to produce the error. i think the first one is the only that could possibly be supported in tests:
* use a SQL insert statement either in the console or using psql
* remove the model validation temporarily, restart console and create there
* remove the UI AND model validation temporarily, restart console and create there

**Comment by samudary** [comment]
Got it! That context is helpful, thanks. I'll get a PR going
