### ISSUE TITLE
Consolidate navbar display logic

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#967]
Our current solution for determining whether to display the nav bar is spread across several places:
* layouts:
    * `application.html.erb`
    * `without_navbar.html.erb`
    * `_navbar.html.erb`
    * `_without_navbar.html.erb`
* controllers:
    * Each individual controller where we want to toggle the navbar
* specs:
    * Request specs for each controller

Inspired by @gamecat2d's question about how best to test the changes in #966, @h-m-m and i discussed ways to consolidate our solution in a single place for future maintainability and also be tested in one place.

One potential solution is to:
* consolidate the two layouts into a single one that applies across the whole site
* have it call a helper method that is given the current_controller and:
    * checks whether it is one where we want to toggle the navbar
    * whether to display the navbar
* the testing would then all be consolidated to a unit test of the helper method

**Comment by gamecat2d** [comment]
Sorry for my english. 

I'm new in Ruby (and Rails too) but in the docs i found the [current_page?](https://apidock.com/rails/v6.1.3.1/ActionView/Helpers/UrlHelper/current_page%3F) method.

What do you think about having in memory (or in database to configure it with the back office) the list of controllers/actions where the navbar need to be hidden and reduce it to a boolean value to display or not the menu in the layout ?

Something like (it's not working just an idea) :
```
<% if !hidden_actions.inject(false) { |acc, actions| acc || current_page?(actions)} %>
the navbar
<% end %>
```

Or a hash to be quicker with the controller as a key to know in O(1) the case where the current controller is not concerned because `hidden_actions[current_controller].nil?`

Best regards and stay safe !

**Comment by h-m-m** [comment]
Hi, @gamecat2d!

I'm not sure what will work here, since I haven't tried it myself. In addition to `current_page?` you have some other options available. I think `params[:controller]` and `params[:action]` might work, and there might be `controller_name` and `action_name` methods.

Also, I think @exbinary's suggestion in this issue is to have all the logic and conditionals in a method that's outside of the view. We haven't been testing views directly in this project. Rails makes testing logic in the views difficult. 

For some additional context, when @exbinary and I were talking about this earlier today we were thinking that we'll probably get future requests to change which pages have the nav bar and which pages don't.

Since we probably will get those future requests, I'd prefer a solution where, if I want to make those changes, I only have to change one or two lines of code and also change one test. And since Rails makes testing views difficult, it would be nice if the code I have to change is not in the view

Thanks again for volunteering to look into this. Please let me know if you have any further questions

**Comment by h-m-m** [comment]
> What do you think about having in memory (or in database to configure it with the back office) the list of controllers/actions where the navbar need to be hidden and reduce it to a boolean value to display or not the menu in the layout ?

Oh, I forgot to answer your question about having in memory. I think that's is fine. I'd even be okay with starting with an array that we manually save in the code somewhere. We can always then move it to a database later once the basic feature is in place

**Comment by h-m-m** [comment]
Completed with @gamecat2d's work merged in!
