### ISSUE TITLE
Newly registered user is presented a Feedback option but not authorized to access it

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#992]
Steps to recreate:
1. Register for a new account, confirm email
2. Click on the Feedback button in the nav bar

Actual:
User is shown the following message:
> Sorry, you aren't authorized to do that.
If you think this is wrong, please contact your administrator.

Expected:
User is either able to provide feedback or not shown the feedback button

H/T @vurtn for reporting in #963 .

**Comment by bobmazanec** [comment]
Reproduced in 81ba8f0

> Expected:
> User is either able to provide feedback or not shown the feedback button

I see that `SoftwareFeedbacksController` is derived from `AdminController`, so my first (newbie!) guess is that this is meant only for Admin users, and I expect few new Users are created as Admins.

So—in newbie-friendly (over-?)specificity 🤓—is this the desired/expected behavior?

## Admin user sees Feedback button
**Given** I am signed in as an Admin User
**When** I am on a page with the navbar (e.g., `/announcements`, `/community_resources`)
**Then**
- I see the [Feedback] navbar button **and**
- it is enabled

![image](https://user-images.githubusercontent.com/2031462/142490387-f8f3936e-87aa-4843-83d9-0079d07688a4.png)

## Non-Admin user does not see Feedback button
**Given** I am signed in as a non-Admin User
**When** I am on a page with the navbar (e.g., `/announcements`, `/community_resources`)
**Then** I do not see the [Feedback] navbar button

?
